fix: pipes

diff --git a/check-code-freeze/action.yml b/check-code-freeze/action.yml
--- a/check-code-freeze/action.yml
+++ b/check-code-freeze/action.yml
@@ -18,7 +18,7 @@ runs:
           export RESPONSE=$(
             curl -H "Authorization: Bearer ${{ inputs.github-token }}" -H "Accept: application/vnd.github+json" https://api.github.com/repos/stampedeapp/freeze/contents/freeze
           )
-          grep $RESPONSE "Not Found" || echo "reason=$(echo $RESPONSE | jq -r 'content' | base64 -d)" >> $GITHUB_OUTPUT
+          echo $REPONSE | grep "Not Found" || echo "reason=$(echo $RESPONSE | jq -r 'content' | base64 -d)" >> $GITHUB_OUTPUT
       - name: Fail if file exists
         if: steps.check-file.outputs.reason != ''
         shell: bash
